chore: make site description visible as intended
theNewDynamic/gohugo-theme-ananke pull request #435
Opened 2021-09-12 05:47 UTC by ivanilves

I have the same issue as @corch here https://github.com/theNewDynamic/gohugo-theme-ananke/issues/238

`.Params.description` gets ignored by the header templates while `.Site.Params.description` works indeed.

2021-10-01 17:06 UTC, regisphilibert requested changes
I believe the intent is the following:

Use `.Params.description` if found,
or fallback on `site.Params.description`.

The easiest way to achieve this is to use `.Param "description"`. [See Param](https://gohugo.io/functions/param/#readout)

2022-02-07 10:44 UTC, closed without merging

2022-03-09 18:35 UTC, emacsen commented
I have a fresh installation (March 2022) and this is still not working out of the box with params.description, or any version of that as I can tell.

I've tried params.description, param.description site.params.description, site.param.description, and none of them appear to work with displaying the description in the text, though they do appear in the header metadata of the page.

2022-08-22 18:01 UTC, sebandrei commented
I'm having an issue with this as well. The site description is set in the config.toml file but does not display in the header. Is this still an unresolved bug?

2022-08-22 18:05 UTC, sebandrei commented
Quick update: I checked out the code posted by regisphilibert and replaced .Params.description with .Site.Params.decription in the partials/site-header.html file. This fixed the issue for me.