Access Disqus shortname from canonical location
theNewDynamic/gohugo-theme-ananke pull request #660
Opened 2023-10-24 17:48 UTC by jmooring

Prepare for deprecation described [here](https://github.com/gohugoio/hugo/commit/2eca1b3cc1cd03fee40c0abcdc61dab1016c0475).

This is a backwards compatible change.

2023-11-21 20:12 UTC, regisphilibert requested changes

2023-11-21 20:12 UTC, regisphilibert commented on layouts/_default/single.html
> +      {{ if .Site.Config.Services.Disqus.Shortname }}
Hi @jmooring and thank you for this! 

I wonder if there is a way to test both values as we'd like the theme to be retro compatible for some months at least.

Maybe just `{{ with .Site.DisqusShortname | or .Site.Config.Services.Disqus.Shortname }}` ?

2023-11-21 21:00 UTC, jmooring commented on layouts/_default/single.html
> +      {{ if .Site.Config.Services.Disqus.Shortname }}
.Site.Config.Services.Disqus.Shortname looks for that config key, falling back to site.DisqusShortname.

2023-11-22 00:14 UTC, regisphilibert commented on layouts/_default/single.html
> +      {{ if .Site.Config.Services.Disqus.Shortname }}
Since which version?

2023-11-22 01:03 UTC, jmooring commented on layouts/_default/single.html
> +      {{ if .Site.Config.Services.Disqus.Shortname }}
v0.41
<https://github.com/gohugoio/hugo/commit/4ddcf52ccc7af3e23109ebaac1f0486087a212ba>

`.Site.Config.Services.Disqus.Shortname` falls back to `disqusShortname`
`.Site.Config.Services.GoogleAnalytics.ID` falls back to `googleAnalytics`

and added in v0.55.0...

`.Site.Config.Services.RSS.Limit` falls back to `rssLimit`

2023-11-22 16:05 UTC, merged