Move to x.com
theNewDynamic/gohugo-theme-ananke pull request #756
Opened 2024-10-22 16:04 UTC by melroy89

Follow-up after: https://github.com/theNewDynamic/gohugo-theme-ananke/pull/652

2024-10-23 22:52 UTC, davidsneighbour requested changes

2024-10-23 22:52 UTC, davidsneighbour commented on config/_default/params.toml
> +label = "X"
Leaving that at Twitter is an opiniated decision. There is a x-twitter config further down the networks list that is labelled X. The changes to the share link are probably required (down under x-twitter too).

2024-10-24 08:53 UTC, melroy89 commented on config/_default/params.toml
> +label = "X"
Owh I see. That is very confusing to also have an x-Twitter option. I would just call it x.

2024-10-24 09:01 UTC, davidsneighbour commented on config/_default/params.toml
> +label = "X"
I wanted it to be longer, and x-twitter is the slug Fontawesome is using... But I am flexible. Put it in the PR... one character slugs might lead to issues.

2024-10-24 11:07 UTC, closed without merging