Do not cache share links
theNewDynamic/gohugo-theme-ananke pull request #757
Opened 2024-10-22 16:19 UTC by melroy89

You can't just cache the share links, that will result into every blog post having the same URL.

Just use `partial` on the getShareLink.html. So now each post will show the correct URL to share the post via social media or alike.

2024-10-22 16:20 UTC, melroy89 commented on layouts/partials/social/share.html
> +      {{- $href := partial "func/getShareLink.html" $options $options -}}
Why is there two times `$options`?

2024-10-22 16:22 UTC, melroy89 commented on layouts/partials/social/share.html
> +      {{- $href := partial "func/getShareLink.html" $options $options -}}
Since we now use `partial` instead of `partialCached`, I believe we can just pass 1x the `$options`.

2024-10-23 22:47 UTC, davidsneighbour commented
False. There is a bug in the logic of the partial, that is true. But we CAN and will cache those links. A share link must be cacheable for a specific page. Check the $options dict. `page` here might refer to the outer list page a post is listed on, which is what ruins the cache if you implement share links on list pages. What this needs is `$context` (defined in the first line) instead of `page` in the options and then they (should be/are) individual caches per post object (if `$context` doesn't walk into the same trap). I'll need to check that though, it might be that I will inline the sharelink generation.

2024-10-23 22:49 UTC, davidsneighbour requested changes

2024-10-23 22:49 UTC, davidsneighbour commented on layouts/partials/social/share.html
> +      {{- $href := partial "func/getShareLink.html" $options -}}
nope ;) see my comment. `{{- $options := (dict "context" $context "setup" $setup -}}` should do the trick with unchanged `partialCached` line.

2024-10-24 08:44 UTC, melroy89 commented on layouts/partials/social/share.html
> +      {{- $href := partial "func/getShareLink.html" $options -}}
Sorry what? I don't see your comment.

2024-10-24 08:59 UTC, davidsneighbour commented
Something along the lines of this, not tested yet:

https://github.com/theNewDynamic/gohugo-theme-ananke/pull/763

2024-10-24 09:52 UTC, davidsneighbour approved these changes

2024-10-24 09:55 UTC, davidsneighbour commented
I am going to merge this now. I opened an issue for going to look at caching after the release.

https://github.com/theNewDynamic/gohugo-theme-ananke/issues/764

2024-10-24 09:58 UTC, merged